use_frameworks!

platform :ios, '10.0'

target 'JKProgressHUD_Example' do
  pod 'JKProgressHUD', :path => '../'
  pod 'JKSwiftExtension'
  pod 'SnapKit'
  
  target 'JKProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
