use_frameworks!

platform :ios, '9.0'

target 'JKProgressHUD_Example' do
  pod 'JKProgressHUD', :path => '../'
  pod 'JKSwiftExtension'

  target 'JKProgressHUD_Tests' do
    inherit! :search_paths

  end
  
end
